# Setup
title:        张起灵
tagline:      我是一个变态
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       赵申侃  
  url:        https://github.com/zhaoshenkan?tab=stars 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
